mysite/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

mysite/mdn/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # path('')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('blog/', include("blog.urls")),
    path('mdn/', include("mdn.urls")),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/blog/models.py
# import urllib2
# import mimetypes

from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Category(models.Model):
    name = models.CharField(max_length=32)
    class Meta:
        verbose_name_plural = "Categories"
        def __unicode__(self):
            return self.name
            
class Tag(models.Model):
    name = models.CharField(max_length=32)
    def __unicode__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name='blog_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
        

mysite/mdn/models.py
from django.db import  models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. science fiction)')
    
    def __str__(self):
        return self.name

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{self.last_name}, {self.first_name}'
        
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return '{self.id} ({self.book.title})'

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/blog/views.py
from django.views import generic
from .models import Post

class PostList(generic.ListView):
    # queryset = Post.objects.filter(status=1).order_by('-created_on')[:2]
    queryset = Post.objects.filter(status=1).order_by('-created_on')[:5]
    template_name = 'blog/index.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

mysite/mdn/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views import generic

# Create your views here.
from .models import  Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Blog</title>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>

<body>
    <nav class="navbar navbar-expand-md topnav">
        <div class="container">
            <div class="navbar-header">
                <a href="#">
                    <img id="logo-main" src="{% static 'blog/images/hacker.svg' %}" width="80px"> HackBoards
                </a>
            </div>

            <div class="col-sm-3 col-md-3 pull-right">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>

            <!--<ul class="nav navbar-nav ml-auto">-->
            <!--<li class="nav-item from-inline">-->
            <!--  <a class="btn btn-sm btn-primary px-3"  style="font-weight: bold;"  href="#">Join</a>-->
            <!--</li>-->
            <!--<li class="nav-item">-->
            <!--  <a class="btn text-dark" style="font-weight: bold;" href="#" style="">Sign&nbsp;In</a>-->
            <!--</li>-->
            <!--</ul>-->
        </div>
    </nav>

    <nav class="navbar navbar-expand-md navbar-default" role="navigation">
        <div class="container">
            <!-- <a class="navbar-brand" href="#">
                <img src="{% static 'blog/images/bootstrap-solid.svg' %}" width="36" height="36" alt="">
              </a> -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavigation" aria-controls="mainNavigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="mainNavigation">
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <!-- <li class="nav-item"> -->
                        <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Trading Services</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#">Trading</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="#">Crypto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Wallet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Network</a>
                    </li>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">News</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                </ul>
            </div>
            <!-- <ul class="nav navbar-nav ml-auto ">
            <li>
                <a href="#" class="nav-link"><i class='fab fa-twitter' style='font-size:24px'></i></a>
            </li>
            <li>
                <a href="#" class="nav-link"><i class='fab fa-facebook-f' style='font-size:24px'></i></a>
            </li>
            <li>
                <a href="#" class="nav-link"><i class='fab fa-telegram' style='font-size:24px'></i></a>
            </li>
          </ul> -->
            <div class="site-social-media">
                <a class="btn-floating btn-lg btn-fb" type="button" role="button"><i class="fab fa-facebook " style="font-size: 24px;"></i></a>
                <!--Twitter-->
                <a class="btn-floating btn-lg btn-tw" type="button" role="button"><i class="fab fa-twitter " style="font-size: 24px;"></i></a>
                <!--Youtube-->
                <a class="btn-floating btn-lg btn-yt" type="button" role="button"><i class="fab fa-youtube " style="font-size: 24px;"></i></a>
            </div>
        </div>

    </nav>

    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %} {% block footer %} {% include 'blog/footer.html' %} {% endblock footer %}

</body>

</html>

mysite/blog/templates/blog/footer.html
{% block footer %}
{% load static %}

<style>
  /*FOOTER*/
  footer {
    background: #2D2D32;
    /* background: -webkit-linear-gradient(59deg, #3A6073, #16222A); */
    /* background: linear-gradient(59deg, #3A6073, #16222A); */
    color: white;
    margin-top: 100px;
  }

  footer a {
    color: #fff;
    font-size: 14px;
    transition-duration: 0.2s;
  }

  footer a:hover {
    color: #FA944B;
    text-decoration: none;
  }

  .copy {
    font-size: 12px;
    padding: 10px;
    border-top: 0.5px solid #FFFFFF;
  }

  .footer-middle {
    padding-top: 2em;
    color: white;
  }


  /*SOCİAL İCONS*/

  /* footer social icons */

  ul.social-network {
    list-style: none;
    display: inline;
    margin-left: 0 !important;
    padding: 0;
  }

  ul.social-network li {
    display: inline;
    margin: 0 5px;
  }

  /* footer social icons */
  .social-network a.icoFacebook:hover {
    background-color: #3B5998;
  }

  .social-network a.icoLinkedin:hover {
    background-color: #007bb7;
  }


  .social-network a.icoYoutube:hover {
    background-color: #bb0000;
  }

  .social-network a.icoTwitter:hover {
    background-color: #00aced;
  }

  .social-network a.icoFacebook:hover i,
  .social-network a.icoTwitter:hover i,
  .social-network a.icoYoutube:hover i,
  .social-network a.icoLinkedin:hover i {
    color: #fff;
  }

  .social-network a.socialIcon:hover,
  .socialHoverClass {
    color: #44BCDD;
  }

  .social-circle li a {
    display: inline-block;
    position: relative;
    margin: 0 auto 0 auto;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
    text-align: center;
    width: 30px;
    height: 30px;
    font-size: 15px;
  }

  .social-circle li i {
    margin: 0;
    line-height: 30px;
    text-align: center;
  }

  .social-circle li a:hover i,
  .triggeredHover {
    -moz-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    -ms--transform: rotate(360deg);
    transform: rotate(360deg);
    -webkit-transition: all 0.2s;
    -moz-transition: all 0.2s;
    -o-transition: all 0.2s;
    -ms-transition: all 0.2s;
    transition: all 0.2s;
  }

  .social-circle i {
    color: #595959;
    -webkit-transition: all 0.8s;
    -moz-transition: all 0.8s;
    -o-transition: all 0.8s;
    -ms-transition: all 0.8s;
    transition: all 0.8s;
  }

  .social-network a {
    background-color: #F9F9F9;
  }
</style>

<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <h4>Lorem Ipsum</h4>
            <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.
              There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is
              pain...</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <!--Column1-->
          <div class="footer-pad">
            <h4>Heading 3</h4>
            <ul class="list-unstyled">
              <li><a href="#">Parks and Recreation</a></li>
              <li><a href="#">Public Works</a></li>
              <li><a href="#">Police Department</a></li>
              <li><a href="#">Fire</a></li>
              <li><a href="#">Mayor and City Council</a></li>
              <li>
                <a href="#"></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <h4>Follow Us</h4>
          <ul class="social-network social-circle">
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook"></i></a></li>
            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fab fa-twitter"></i></a></li>
            {% comment %} <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fab fa-linkedin"></i></a></li> {% endcomment %}
            <li><a href="#" class="icoYoutube" title="Youtube"><i class="fab fa-youtube"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 copy">
          <p class="text-center">&copy; Copyright 2019 - HackBoards. All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>
{% endblock footer %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %}

<style>
  .breadcumb {
    background-color: none!important;
  }
  .card-text {
    line-height: 1.6;
  }
</style>
<div class="container">
  <div class="row">
    <!--<div class="col-md-8 left  top">-->
      <!--</div>-->
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">{{ post.category }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ post.title|slice:"24" }}...</li>
          </ol>
      </nav>
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class="text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

mysite/blog/templates/blog/sidebar-home.html
{% block sidebarhome %}


<style>
        .sidebar-card {
            border: none;
        }

        /* .sidebar-home {
            box-shadow: 1 16px 48px #E3E7EB;
        }

        .sidebar-home.card {
            box-shadow: 0 16px 48px #E3E7EB;
        }

        .sidebar-home.card.card-body {
          border: none;
        } */

        #idHomeSidebar {
          background-color: white;
          /* margin-left: 2px; */
        }
        
        .media > a {
            text-decoration: none;
            font-size: 12px;
        }

        .media {
            padding: 10px;
        }

</style>


<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right " style="background-color: white;">
  <div class="sidebar-home" id="idHomeSidebar" style="background-color: white;">
    <!-- <div class="section-heading mt-3 ml-2"> -->
    <div class="section-heading mt-3">
        <h5>Most Popular</h5>
    </div>

    {% for post in post_list %}
    <div class="media">
    <img class="mr-3" src="https://via.placeholder.com/100" alt="Generic placeholder image">
    <div class="media-body">
        <a href="{% url 'blog:post_detail' post.slug  %}">{{ post.title|slice:"60" }}</a>
        {% comment %} Cras sit amet nibh libero, in gravida nulla. {% endcomment %}
    </div>
    </div>
    {% endfor %}

{% comment %}
    {% for post in post_list %}
    <div class="card sidebar-card">
      <div class="card-body">
          <a href="{% url 'blog:post_detail' post.slug  %}">{{ post.title|slice:"60" }}</a>
          <p class="card-text text-muted h6">{{ post.Author }} | {{ post.created_on}} </p>
      </div>
    </div>
    {% endfor %}
{% endcomment %}

  </div>
</div>

{% endblock sidebarhome %}

mysite/blog/templates/blog/sidebar.html
{% block sidebar %}


<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>


<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">

<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#" class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}

mysite/blog/templates/blog/temp/carouel-multiple-item.html
<div class="container my-4">

    <p class="font-weight-bold">Bootstrap carousel multiple items is an improved version of the standard bootstrap
      carousel which allows you to put inside more than one element.</p>

    <p><strong>Detailed documentation and more examples of Bootstrap grid you can find in our <a href="https://mdbootstrap.com/docs/jquery/javascript/carousel/"
          target="_blank">Bootstrap Carousel Docs</a>.</p>

    <hr class="my-4">

    <!--Carousel Wrapper-->
    <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

      <!--Controls-->
      <div class="controls-top">
        <a class="btn-floating" href="#multi-item-example" data-slide="prev"><i class="fa fa-chevron-left"></i></a>
        <a class="btn-floating" href="#multi-item-example" data-slide="next"><i class="fa fa-chevron-right"></i></a>
      </div>
      <!--/.Controls-->

      <!--Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
        <li data-target="#multi-item-example" data-slide-to="1"></li>
        <li data-target="#multi-item-example" data-slide-to="2"></li>
      </ol>
      <!--/.Indicators-->

      <!--Slides-->
      <div class="carousel-inner" role="listbox">

        <!--First slide-->
        <div class="carousel-item active">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(34).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(18).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(35).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.First slide-->

        <!--Second slide-->
        <div class="carousel-item">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(60).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(47).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(48).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.Second slide-->

        <!--Third slide-->
        <div class="carousel-item">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/4-col/img%20(53).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/4-col/img%20(45).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/4-col/img%20(51).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.Third slide-->

      </div>
      <!--/.Slides-->

    </div>
    <!--/.Carousel Wrapper-->


  </div>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

<!-- {% comment %}
<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }}</li>
  {% endfor %}
</ul>
{% endcomment %} -->

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}"} method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if question_list %}
<ul>
  {% for question in question_list %}
    <li>
      <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>No polls are available</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes | pluralize}}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>